name:                scotty-bytestring-cookie
version:             0.1.0.0
github:              srdqty/scotty-bytestring-cookie
license:             BSD3
author:              Sofia Donataccio
maintainer:          srdqty@gmail.com
copyright:           Copyright (c) 2018 Sofia Donataccio

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Functions for reading and writing HTTP cookies with Scotty.
description: >
  Functions for reading and writing HTTP cookies with Scotty. The inputs and
  outputs uses ByteStrings instead of Text.
category: Web

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10.02 && < 0.11
  - case-insensitive >= 1.0.0.1 && < 1.3
  - cookie >= 0.4.4 && < 0.5
  - http-types >= 0.8.2 && < 0.13
  - mtl >= 2.1.2 && < 2.3
  - scotty >= 0.11.2 && < 0.12
  - scotty-bytestring >= 0.1.0.0 && < 0.2
  - time >= 1.8.0.2 && < 1.10
  - wai >= 3.0.0 && < 3.3

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

tests:
  scotty-bytestring-cookie-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -O2
    dependencies:
      - scotty-bytestring-cookie
      - hspec == 2.*
      - hspec-wai >= 0.6.3
      - text >= 0.11.3.1 && < 1.3
